STYLES = [
    {"key": "beach", "aliases": ["biển", "bãi biển", "sea", "beach"]},
    {"key": "resort", "aliases": ["nghỉ dưỡng", "resort", "chill", "thư giãn"]},
    {"key": "mountain", "aliases": ["núi", "leo núi", "mountain", "trekking"]},
    {"key": "adventure", "aliases": ["mạo hiểm", "khám phá", "adventure", "phiêu lưu", "thám hiểm"]},
    {"key": "culture", "aliases": ["văn hóa", "lịch sử", "culture", "history", "di tích", "bảo tàng"]},
    {"key": "food", "aliases": ["ẩm thực", "ăn uống", "food", "ẩm thực địa phương", "đặc sản"]},
    {"key": "island", "aliases": ["đảo", "island", "cù lao"]},
    {"key": "camping", "aliases": ["cắm trại", "camping", "dã ngoại"]},
    {"key": "family", "aliases": ["gia đình", "family", "trẻ em", "kid", "thiếu nhi"]},
    {"key": "couple", "aliases": ["cặp đôi", "couple", "tình nhân", "honeymoon"]},
    {"key": "group", "aliases": ["nhóm", "team", "công ty", "bạn bè", "group", "team building"]},
    {"key": "shopping", "aliases": ["mua sắm", "shopping", "chợ", "siêu thị"]},
    {"key": "spa", "aliases": ["spa", "massage", "thư giãn"]},
    {"key": "golf", "aliases": ["golf", "sân golf"]},
    {"key": "festival", "aliases": ["lễ hội", "festival", "sự kiện"]},
    {"key": "pagoda", "aliases": ["chùa", "đền", "miếu", "pagoda", "temple"]},
    {"key": "isolation", "aliases": ["tĩnh lặng", "yên tĩnh", "ẩn dật", "isolation", "retreat"]},
    {"key": "solo", "aliases": ["một mình", "cá nhân", "solo", "độc hành"]},
]
